name: deploy-action
run-name: ${{ github.actor }} is deploying
on: [push]
jobs:
  deploy-to-main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
      - run: npm install
      - run: npm run build
      - name: Move build output
        run: .\scripts\move-out-dir.ps1
        shell: powershell
